name: Linux

on: [push]

jobs:
  system:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Cache (ccache)
      uses: actions/cache@v1.0.3
      with:
        path: build/ccache
        key: system_ccache

    - name: Cache (downloads)
      uses: actions/cache@v1.0.3
      with:
        path: build/downloads
        key: system_downloads

    - name: Cache (submodules)
      uses: actions/cache@v1.0.3
      with:
        path: .git/modules
        key: system_submodules

    - name: Build
      run: ./scripts/build_release.sh --system

  portable:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Cache (ccache)
      uses: actions/cache@v1.0.3
      with:
        path: build/ccache
        key: portable_ccache

    - name: Cache (downloads)
      uses: actions/cache@v1.0.3
      with:
        path: build/downloads
        key: portable_downloads

    - name: Cache (submodules)
      uses: actions/cache@v1.0.3
      with:
        path: .git/modules
        key: portable_submodules

    - name: Build
      run: ./scripts/build_release.sh --portable

  portable-osquery:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Cache (ccache)
      uses: actions/cache@v1.0.3
      with:
        path: build/ccache
        key: portable_osquery_ccache

    - name: Cache (downloads)
      uses: actions/cache@v1.0.3
      with:
        path: build/downloads
        key: portable_osquery_downloads

    - name: Cache (submodules)
      uses: actions/cache@v1.0.3
      with:
        path: .git/modules
        key: portable_osquery_submodules

    - name: Build
      run: ./scripts/build_release.sh --portable-osquery

